{{- if .Values.sftpConfig.authorizedKeys }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sftp-server.fullname" . }}-authorized-keys
data:
  id_rsa.pub: {{ .Values.sftpConfig.authorizedKeys | quote }}
{{- end }}
