apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftp-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sftp-server.name" . }}
    helm.sh/chart: {{ include "sftp-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sftp-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sftp-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: sftp-config
              mountPath: /etc/sftp/
          livenessProbe:
            tcpSocket:
              port: 22
          readinessProbe:
            tcpSocket:
              port: 22
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: sftp-config
        configMap:
          name: {{ include "sftp-server.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
